FROM debian:12-slim

RUN dpkg --add-architecture arm64 && dpkg --add-architecture armhf && dpkg --add-architecture i386 && \
    apt-get update -qq && \
    DEBIAN_FRONTEND="noninteractive" apt-get install -qqy --no-install-recommends \
    build-essential cmake make pkg-config \
    gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
    gcc-i686-linux-gnu g++-i686-linux-gnu \
    libwayland-dev:armhf libwayland-dev:arm64 libwayland-dev:i386 libwayland-dev:amd64 \
    crossbuild-essential-armhf crossbuild-essential-arm64 \
    openjdk-17-jdk:armhf openjdk-17-jdk:arm64 openjdk-17-jdk:i386 openjdk-17-jdk:amd64 && \
    apt-get clean -y && rm -rf /var/lib/apt/lists/*

COPY toolchain/* /toolchain/
WORKDIR /work
