name: New feature submissions
description: Write down your suggestions for new features.
title: "[Feat]: "
labels: [ "enhancement" ]
body:
    -   type: markdown
        attributes:
            value: "# TouchController feature request"
    -   type: checkboxes
        id: feature_check
        attributes:
            label: Checklist
            description: "Before reporting, please confirm the following:"
            options:
                -   label: This feature has not been requested before (you can search [here](https://github.com/TouchController/TouchController/issues?q=is%3Aissue)).
                    required: true
                -   label: This feature is not in [Pull Requests](https://github.com/TouchController/TouchController/pulls)
                    required: true
                -   label: This feature has not been added in the latest version of the TouchController mod.
                    required: true
                -   label: "I am aware that: If I only have some ideas rather than new features, they need to be submitted in the [Discussions](https://github.com/TouchController/TouchController/discussions/new?category=%E6%83%B3%E6%B3%95)."
                    required: true
    -   type: input
        id: feature_summary
        attributes:
            label: Summary
            description: Please briefly describe the new feature you'd like to add.
            placeholder: |
                <Summary of this feature>
    -   type: textarea
        id: feature_details
        attributes:
            label: Details
            description: Please describe the reasons why this feature is needed, as well as the content of the new feature in detail.
            placeholder: |
                <the reasons why this feature is needed and the content of the new feature in detail>
    -   type: markdown
        attributes:
            value: "### Thank you for supporting TouchController!"
