"Common properties in combine"
combine_version = "0.0.1"
combine_home_page = "https://github.com/TouchController/TouchController"
combine_sources_page = "https://github.com/TouchController/TouchController"
combine_issue_tracker = "https://github.com/TouchController/TouchController/issues"
combine_license = "LGPL-3.0-or-later"
combine_description = "COMpose Brought to mINEcraft. Bring your favorite UI framework to Minecraft!"
