when:
  - event: push
    branch: master

clone:
  git:
    image: woodpeckerci/plugin-git
    environment:
      http_proxy:
        from_secret: GIT_PROXY
      https_proxy:
        from_secret: GIT_PROXY

steps:
  - name: build
    image: docker.io/peaceiris/mdbook:v0.5.0
    directory: touchcontroller/wiki
    commands:
      - sed -i 's+/*FOOTER TEMPLATE HERE*/+"'"${FOOTER_TEMPLATE}"'"+' "custom.js"
      - mdbook build
    environment:
      FOOTER_TEMPLATE:
        from_secret: FOOTER_TEMPLATE
